[bundles]
dockerCompose = ["springBoot-dockerCompose", "springAi-springBootDockerCompose"]
testcontainers = ["springBoot-testcontainers", "testcontainers-junitJupiter", "testcontainers-qdrant"]

[versions]
java = "24"
kotlin = "2.2.21"
kotlin-logging = "7.0.14"
ktlint = "14.0.1"
spring-ai = "2.0.0-M2"
spring-boot = "4.0.2"
spring-cloud = "2025.1.0"
spring-functions-catalog = "5.2.0"
spring-dependency-management = "1.1.7"

[libraries]
# Spring Boot
springBoot-starterActuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
springBoot-starterValidation = { module = "org.springframework.boot:spring-boot-starter-validation" }
springBoot-starterWebmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }

# Spring AI
springAi-bom = { module = "org.springframework.ai:spring-ai-bom", version.ref = "spring-ai" }
springAi-advisorsVectorStore = { module = "org.springframework.ai:spring-ai-advisors-vector-store" }
springAi-starterModelOpenai = { module = "org.springframework.ai:spring-ai-starter-model-openai" }
springAi-starterVectorStoreQdrant = { module = "org.springframework.ai:spring-ai-starter-vector-store-qdrant" }
springAi-tikaDocumentReader = { module = "org.springframework.ai:spring-ai-tika-document-reader" }

# Spring Cloud
springCloud-bom = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "spring-cloud" }
springCloudFn-bom = { module = "org.springframework.cloud.fn:spring-functions-catalog-bom", version.ref = "spring-functions-catalog" }
springCloud-functionContext = { module = "org.springframework.cloud:spring-cloud-function-context" }
springCloudFn-fileSupplier = { module = "org.springframework.cloud.fn:spring-file-supplier" }

# Kotlin
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }

# Serialization
jackson-moduleKotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }

# Logging
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }

# Docker Compose
springBoot-dockerCompose = { module = "org.springframework.boot:spring-boot-docker-compose" }
springAi-springBootDockerCompose = { module = "org.springframework.ai:spring-ai-spring-boot-docker-compose" }

# Test
springBoot-starterActuatorTest = { module = "org.springframework.boot:spring-boot-starter-actuator-test" }
springBoot-starterValidationTest = { module = "org.springframework.boot:spring-boot-starter-validation-test" }
springBoot-starterWebmvcTest = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
kotlin-testJunit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
junit-platformLauncher = { module = "org.junit.platform:junit-platform-launcher" }

# Testcontainers
springBoot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }
testcontainers-junitJupiter = { module = "org.testcontainers:testcontainers-junit-jupiter" }
testcontainers-qdrant = { module = "org.testcontainers:testcontainers-qdrant" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependencyManagement = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
